version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      # Check for updates to go modules every weekday
      interval: "daily"
