name: CI
on: [push, pull_request]

jobs:
  build_test:
    name: Build and Test
    strategy:
      matrix:
        go: ['1.12', '1.13', '1.14', '1.15', '1.16']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-go@v2.1.3
      with:
        go-version: ${{ matrix.go }}
        stable: false
    - name: Build and Test
      run: go test ./...
